name: Flutter Windows Build

on:
  push:
    branches:
      - forking  # Trigger workflow on push to the 'forking' branch
  pull_request:
    branches:
      - forking  # Trigger workflow on pull request to the 'forking' branch

jobs:
  build:
    runs-on: windows-latest  # This sets up the environment for Windows

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Flutter using subosito/flutter-action
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.1'  # Use your exact Flutter version here

      # Step 3: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 4: Build the Windows app
      - name: Build Windows app
        run: flutter build windows --release

      # Optional: Step 5: Upload the build artifacts (to download later)
      - name: Upload Windows Build
        uses: actions/upload-artifact@v3
        with:
          name: windows-build
          path: build/windows/runner/Release/your_project_name.exe
